version: '3.8'
# --- BEFORE DEPLOYMENT ---
# docker network create --driver=overlay --opt encrypted --attachable web
services:
  ingress:
    image: coryagroup/agassi:latest
    secrets:
      - lets-encrypt-account
      - corya-group-default-key
      - corya-group-default-cert
    configs:
      - lets-encrypt-email
    environment:
      ETCD: etcd-01:2379,etcd-02:2379,etcd-03:2379
      ACME_KEY: /run/secrets/lets-encrypt-account
      DEFAULT_KEY: /run/secrets/corya-group-default-key
      DEFAULT_CRT: /run/secrets/corya-group-default-cert
      EMAIL: /lets-encrypt-email
      STAGING: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - etcd
      - web
    ports:
      - 80:80
      - 443:443
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

networks:
  etcd:
    external: true
  web:
    external: true

secrets:
  lets-encrypt-account:
    external: true
  corya-group-default-key:
    external: true
  corya-group-default-cert:
    external: true

configs:
  lets-encrypt-email:
    external: true
