name: Main Branch CI

# For all pushes to the main branch run the tests and push the image to the
# GitHub registry under an edge tag so we can use it for the nightly
# integration tests
on:
  push:
    branches: main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Compile and Publish Image
        uses: matootie/github-docker@v3.1.0
        with:
          accessToken: ${{ github.token }}

      - name: Build and publish "head" Docker image
        uses: VaultVulp/gp-docker-action@1.5.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: main # Provide Docker image name
          image-tag: latest # Provide Docker image tag

      - name: Notify Telegram
        uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.TELEGRAM_USER_ID }} # user id or channel name secret
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }} # token secret
          status: ${{ job.status }} # do not modify this line
